services:
  postgres:
    image: postgres:15-alpine
    container_name: warung-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: warung
      POSTGRES_PASSWORD: warung123
      POSTGRES_DB: warung_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
